[package]
name = "ys-tools"
version = "0.0.1"
authors = ["Aster <192607617@qq.com>"]
description = "A modern source code and asset version management system"
repository = "https://github.com/oovm/YuanShen"
documentation = "https://docs.rs/yuan-shen"
readme = "readme.md"
license = "MPL-2.0"
edition = "2021"
exclude = ["package.json", "tests/**"]

[[bin]]
name = "ys"
path = "app/main.rs"

[[bin]]
name = "源神"
path = "app/zh_hans.rs"

[dependencies]
clap = { workspace = true }
clap_builder = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde_json = { workspace = true }
ys-types = { workspace = true }
ys-storage = { workspace = true }




[dev-dependencies]



[features]
default = []

[package.metadata.docs.rs]
all-features = true
