[package]
name = "ys-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
ys-types = { workspace = true }
limbo = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
dashmap = { workspace = true }
tracing = { workspace = true }
async-trait = "0.1"
