[package]
name = "ys-server"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "A modern source code and asset version management system"
repository = "https://github.com/oovm/YuanShen"
documentation = "https://docs.rs/yuan-shen"
readme = "readme.md"
license = "MPL-2.0"
edition = "2021"
exclude = ["package.json", "tests/**"]

[dependencies]
tokio = { workspace = true, features = ["full"] }
ys-types = { workspace = true }
ys-storage = { workspace = true }
ys-gateway = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tempfile = { workspace = true }

[features]
default = []

[package.metadata.docs.rs]
all-features = true
